# This workflow installs Python dependencies, runs tests, lints, and executes script on manual API trigger
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application with API Trigger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [run_predection]  # Allows external trigger from JavaScript/API

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Stop build on syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings (exit-zero)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest

  run_script:
    runs-on: ubuntu-latest
    needs: build  # Ensures tests & linting pass before running script

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      env:
        PROJECT_NAME: ${{ github.event.client_payload.project_name }}
      run: python script.py

    - name: Commit Log File (Save Outputs)
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add log.txt
        git commit -m "Updated log file"
        git push || echo "No changes to commit"
