name: Run Python Script on Request

on:
  repository_dispatch:
    types: [run_python_script]

permissions:
  contents: read

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      env:
        PROJECT_NAME: ${{ github.event.client_payload.project_name }}
        REQUEST_DATE: ${{ github.event.client_payload.request_date }}
      run: python script.py
